// src/localization/bg.ts
const bg = {
  tabs: {
    incomes: "Доходи",
    deductions: "Облекчения",
    declaration: "Декларация",
    archive: "Архив",
    language: "Език",
    dashboard: "Начало",
  },
  common: {
    error: "Грешка",
    ok: "Готово",
    save: "Запази",
    saved: "Записано",
    saveFailed: "Неуспешен запис",
    loadFailed: "Неуспешно зареждане",
    delete: "Изтрий",
    cancel: "Отказ",
    confirm: "Потвърди",
    close: "Затвори",
    loading: "Зареждане...",
  },
  createTax: {
    title: "Декларация",
    year: "Година",
    income: "Доходи",
    reliefs: "Облекчения",
    review: "Преглед",
    generatePdf: "Преглед за подаване (PDF)",
    exportXlsx: "Експорт (Excel/CSV)",
    saveDraft: "Запази чернова",
    markSubmitted: "Маркирай като подадена",
    draftSaved: "Черновата е запазена.",
    saveFailed: "Неуспешно запазване.",
    noDraft: "Няма запазена декларация.",
    markedSubmitted: "Маркирано като подадена.",
    submitFailed: "Грешка при маркиране.",
    errors: {
      yearRequired: "Моля, въведете година.",
      yearOutOfRange: "Годината е извън допустимия диапазон.",
      amountInvalid: "Невалидна сума.",
      fixErrors: "Моля, коригирайте грешките във формата.",
    },
  },
  declaration: {
    title: "Декларация",
    year: "Година",
    income: "Доходи",
    reliefs: "Облекчения",
    review: "Преглед",
    generatePdf: "Преглед за подаване (PDF)",
    exportXlsx: "Експорт (Excel/CSV)",
    saveDraft: "Запази чернова",
    markSubmitted: "Маркирай като подадена",
    draftSaved: "Черновата е запазена.",
    saveFailed: "Неуспешно запазване.",
    noDraft: "Няма запазена декларация.",
    markedSubmitted: "Маркирано като подадена.",
    submitFailed: "Грешка при маркиране.",
  },
  submit: {
    title: "Подпис и подаване",
    status: "Статус",
    taxDue: "Дължим данък",
    createdAt: "Създадена",
    submittedAt: "Подадена",
    step1: "Генерирай XML",
    step1Desc: "Създай XML за декларацията. Можеш да го свалиш и подпишеш с КЕП.",
    generateXml: "Генерирай XML",
    shareXml: "Сподели XML",
    step2: "Подпиши и подай в портала на НАП",
    step2Desc: "Отвори портала на НАП, подпиши XML с КЕП и подай. Запази входящия номер.",
    openNap: "Отвори портал на НАП",
    step3: "Качи подписан файл и маркирай подаване",
    step3Desc: "Добави подписания файл или потвърждение за подаване. После маркирай като подадена.",
    attachFile: "Добави файл",
    markSubmitted: "Маркирай като подадена",
    payment: "Плащане на данъка",
    paymentDesc: "Можеш да платиш веднага. Сумата ще бъде поставена в клипборда.",
    copyAmount: "Копирай сума",
    goToPay: "Към плащане",
    note: "Бележка",
    notePh: "Описание...",
  },
  pay: {
    title: "Плащане на данъка",
    receiver: "Получател",
    copyIban: "Копирай IBAN",
    reason: "Основание за плащане",
    reasonPh: "Пример: Данък по ЗДДФЛ за {{year}} ЕГН 0000000000",
    copyReason: "Копирай основание",
    amount: "Сума",
    qrTitle: "EPC/SEPA QR код",
    qrNoteEur: "Сканирай в мобилното банкиране. Валидно за SEPA преводи в EUR.",
    qrNoteBgn: "Информативен QR. За SEPA е нужен EUR.",
    shareQr: "Сподели QR",
    saveToArchive: "Запиши в Архив",
  },
  incomes: {
    description: "Описание",
    amount: "Сума",
    date: "Дата",
    add: "Добави ред",
    delete: "Изтрий",
    empty: "Няма записи.",
    total: "Общо",
    placeholders: { description: "Описание" },
    errors: {
      descRequired: "Описание е задължително.",
      amountInvalid: "Невалидна сума.",
      dateInvalid: "Невалидна дата (YYYY-MM-DD).",
      fixErrors: "Поправете грешките.",
    },
  },
  deductions: {
    title: "Облекчения",
    name: "Име",
    amount: "Сума",
    total: "Общо",
    limit: "Лимит: {{limit}} лв.",
    add: "Добави",
    delete: "Изтрий",
    empty: "Няма облекчения.",
    placeholders: { name: "Име на облекчение" },
    errors: {
      nameRequired: "Името е задължително при сума > 0.",
      amountInvalid: "Невалидна сума.",
      overLimit: "Надвишен лимит {{limit}}.",
      fixErrors: "Поправете грешките.",
    },
  },
  archive: {
    title: "Архив",
    open: "Отвори",
    draft: "Чернова",
    submitted: "Подадена",
    empty: "Няма декларации.",
    loadFailed: "Архивът не може да се зареди.",
    deleteFailed: "Изтриването се провали.",
    confirmDelete: "Да изтрия ли декларацията за {{y}}?",
  },
  language: {
    title: "Смяна на език",
    bg: "Български",
    en: "English",
    tip: "Съвет: промяната се отразява до 1 секунда.",
  },
  dashboard: { heading: "ЕДанъци", sub: "Краен срок за ГДД: 30 април" },
  notifications: { title: "Известия" },
  calculators: { title: "Калкулатори" },
};
export default bg;
