// src/localization/en.ts
const en = {
  tabs: {
    incomes: "Incomes",
    deductions: "Deductions",
    declaration: "Declaration",
    archive: "Archive",
    language: "Language",
    dashboard: "Dashboard",
  },
  common: {
    error: "Error",
    ok: "OK",
    save: "Save",
    saved: "Saved",
    saveFailed: "Save failed",
    loadFailed: "Load failed",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    close: "Close",
    loading: "Loading...",
  },
  createTax: {
    title: "Declaration",
    year: "Year",
    income: "Income",
    reliefs: "Reliefs",
    review: "Review",
    generatePdf: "Preview (PDF)",
    exportXlsx: "Export (Excel/CSV)",
    saveDraft: "Save draft",
    markSubmitted: "Mark submitted",
    draftSaved: "Draft saved.",
    saveFailed: "Save failed.",
    noDraft: "No saved declaration.",
    markedSubmitted: "Marked as submitted.",
    submitFailed: "Failed to mark submitted.",
    errors: {
      yearRequired: "Please enter a year.",
      yearOutOfRange: "Year is out of allowed range.",
      amountInvalid: "Invalid amount.",
      fixErrors: "Please fix the errors in the form.",
    },
  },
  declaration: {
    title: "Declaration",
    year: "Year",
    income: "Income",
    reliefs: "Reliefs",
    review: "Review",
    generatePdf: "Preview (PDF)",
    exportXlsx: "Export (Excel/CSV)",
    saveDraft: "Save draft",
    markSubmitted: "Mark submitted",
    draftSaved: "Draft saved.",
    saveFailed: "Save failed.",
    noDraft: "No saved declaration.",
    markedSubmitted: "Marked as submitted.",
    submitFailed: "Failed to mark submitted.",
  },
  submit: {
    title: "Sign and submit",
    status: "Status",
    taxDue: "Tax due",
    createdAt: "Created at",
    submittedAt: "Submitted at",
    step1: "Generate XML",
    step1Desc: "Create the declaration XML. You can download and sign it with a QES.",
    generateXml: "Generate XML",
    shareXml: "Share XML",
    step2: "Sign and file in the NRA portal",
    step2Desc: "Open the NRA portal, sign the XML with a QES and submit. Keep the intake number.",
    openNap: "Open NRA portal",
    step3: "Attach signed file and mark as submitted",
    step3Desc: "Attach the signed file or submission receipt. Then mark as submitted.",
    attachFile: "Attach file",
    markSubmitted: "Mark submitted",
    payment: "Pay the tax",
    paymentDesc: "You can pay now. The amount will be copied to the clipboard.",
    copyAmount: "Copy amount",
    goToPay: "Go to Pay",
    note: "Note",
    notePh: "Description...",
  },
  pay: {
    title: "Pay the tax",
    receiver: "Beneficiary",
    copyIban: "Copy IBAN",
    reason: "Payment reason",
    reasonPh: "Example: PIT for {{year}} EGN 0000000000",
    copyReason: "Copy reason",
    amount: "Amount",
    qrTitle: "EPC/SEPA QR code",
    qrNoteEur: "Scan in your mobile banking. Valid for SEPA transfers in EUR.",
    qrNoteBgn: "Informational QR. EUR is required for SEPA.",
    shareQr: "Share QR",
    saveToArchive: "Save to Archive",
  },
  incomes: {
    description: "Description",
    amount: "Amount",
    date: "Date",
    add: "Add row",
    delete: "Delete",
    empty: "No records.",
    total: "Total",
    placeholders: { description: "Description" },
    errors: {
      descRequired: "Description is required.",
      amountInvalid: "Invalid amount.",
      dateInvalid: "Invalid date (YYYY-MM-DD).",
      fixErrors: "Please fix the errors.",
    },
  },
  deductions: {
    title: "Deductions",
    name: "Name",
    amount: "Amount",
    total: "Total",
    limit: "Limit: {{limit}} BGN",
    add: "Add",
    delete: "Delete",
    empty: "No deductions.",
    placeholders: { name: "Deduction name" },
    errors: {
      nameRequired: "Name is required when amount > 0.",
      amountInvalid: "Invalid amount.",
      overLimit: "Limit exceeded {{limit}}.",
      fixErrors: "Please fix the errors.",
    },
  },
  archive: {
    title: "Archive",
    open: "Open",
    draft: "Draft",
    submitted: "Submitted",
    empty: "No declarations.",
    loadFailed: "Cannot load archive.",
    deleteFailed: "Delete failed.",
    confirmDelete: "Delete declaration for {{y}}?",
  },
  language: {
    title: "Language",
    bg: "Bulgarian",
    en: "English",
    tip: "Tip: tabs refresh within ~1 second.",
  },
  dashboard: { heading: "eTaxes", sub: "Annual return deadline: April 30" },
  notifications: { title: "Notifications" },
  calculators: { title: "Calculators" },
};
export default en;
