/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/submit` | `/submit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/archive` | `/archive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calculators` | `/calculators`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/declaration` | `/declaration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deductions` | `/deductions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/income-sources` | `/income-sources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/pay`; params?: Router.UnknownOutputParams; } | { pathname: `/review`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/submit` | `/submit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/archive` | `/archive`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calculators` | `/calculators`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/declaration` | `/declaration`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/deductions` | `/deductions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/income-sources` | `/income-sources`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/language` | `/language`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/pay${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/submit${`?${string}` | `#${string}` | ''}` | `/submit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/archive${`?${string}` | `#${string}` | ''}` | `/archive${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calculators${`?${string}` | `#${string}` | ''}` | `/calculators${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/declaration${`?${string}` | `#${string}` | ''}` | `/declaration${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/deductions${`?${string}` | `#${string}` | ''}` | `/deductions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/income-sources${`?${string}` | `#${string}` | ''}` | `/income-sources${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/incomes${`?${string}` | `#${string}` | ''}` | `/incomes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/language${`?${string}` | `#${string}` | ''}` | `/language${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/submit` | `/submit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/archive` | `/archive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calculators` | `/calculators`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/declaration` | `/declaration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deductions` | `/deductions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/income-sources` | `/income-sources`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
