name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Type check
        run: npm run tsc

      - name: Unit tests with coverage
        run: npx jest --ci --coverage --runInBand

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Report coverage summary
        if: always()
        run: |
          npx istanbul-cobertura-badger -r coverage/cobertura-coverage.xml -d coverage || true